import type { Metadata } from "next";
import "@app/styles/globals.css";
import JwtContextProvider from "@user/context/JwtContext";

/**
 * Confinguración del SEO.
 */
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

/**
 * Layout principal de la app.
 * @param param0
 * @returns
 */
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <JwtContextProvider>
            <html lang="en">
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0"
                />
                <body className="">{children}</body>
            </html>
        </JwtContextProvider>
    );
}
